###
# Starship configuration
###

###
# Configures the starship schema
###
"$schema" = 'https://starship.rs/config-schema.json'

###
# Configures the add newline
###
add_newline = false

###
# Configures the format
###
format = """
$directory\
$docker_context\
$aws\
$fill\
$git_branch$git_status\
$php\
$python\
$golang\
$rust\
$lua\
$nodejs\
$ruby\
$typst\
$time\
$line_break\
$character
"""

###
# Configures the palette
###
palette = 'gruvbox'

[palettes.gruvbox]
foreground = '#fbf1c7'
background = '#282828'
box = '#3c3836'
line = '#665c54'
primary = '#3c3836'
error = '#cc241d'
success = '#98971a'
color1 = '#458588'
color2 = '#689d6a'
color3 = '#d79921'
color4 = '#d65d0e'
color5 = '#b16286'
color6 = '#b16286'
color7 = '#cc241d'


###
# Configures the directory module
###
[directory]
format = '[$read_only$truncation_symbol](fg:foreground bg:color2)[ $path ](fg:foreground bg:background)'
home_symbol = "󱂵 ~"
read_only = '󰌾 '
read_only_style = ''
truncation_length = 2
truncation_symbol = '󰝰 '

[directory.substitutions]
'/opt/code' = ' code'

###
# Configures the character module
###
[character]
error_symbol = '[χ](bold fg:error)'
format = '$symbol '
success_symbol = '[λ](bold fg:success)'

###
# Configures the fill module
###
[fill]
style = 'bg:background'
symbol = ' '

###
# Configures the git branch module
###
[git_branch]
format = '[ $symbol ](bg:color4 fg:primary)[ $branch ](fg:color6 bg:background)'
symbol = '󰘬'

###
# Configures the git commit module
###
[git_commit]
commit_hash_length = 4
format = "([ 󰓹 ](fg:primary bg:color3)[ $tag ](fg:foreground bg:background))([ 󰜘 ](fg:primary bg:color3)[ $hash ](fg:foreground bg:background))"
only_detached = false
tag_disabled = false
tag_symbol = ''

###
# Configures the git status module
###
[git_status]
format = '[ ](fg:color3 bg:background)$stashed$staged$deleted$renamed$modified$untracked$ahead_behind$conflicted'
stashed = '[](fg:color3 bg:background)[ $count ](fg:foreground bg:background)'
ahead = '[󰁝](fg:color2 bg:background)[ $count ](fg:foreground bg:background)'
behind = '[󰁅](fg:color4 bg:background)[ $count ](fg:foreground bg:background)'
diverged = '[󰃻](fg:color7 bg:background)[ $ahead_count $behind_count ](fg:foreground bg:background)'
conflicted = '[󰅙](fg:color7 bg:background)[ $count ](fg:foreground bg:background)'
deleted = '[󰍴](fg:color3 bg:background)[ $count ](fg:foreground bg:background)'
renamed = '[󰑕](fg:color3 bg:background)[ $count ](fg:foreground bg:background)'
modified = '[󰏫](fg:color3 bg:background)[ $count ](fg:foreground bg:background)'
staged = '[󰐕](fg:color2 bg:background)[ $count ](fg:foreground bg:background)'
untracked = '[󰐕](fg:color2 bg:background)[ $count ](fg:foreground bg:background)'

###
# Configures the time module
###
[time]
disabled = false
format = '[ 󰥔 ](bg:color5 fg:primary)[ $time ](fg:color6 bg:background)'
time_format = '%H:%M'

###
# Configures the aws module
###
[aws]
disabled = true
format = '[ ☁︎ ](fg:primary bg:color7)([ $region ](fg:foreground bg:background))'

###
# Configures the docker context module
###
[docker_context]
disabled = false
format = '[ 󰡣 ](fg:primary bg:color1)([ $context ](fg:foreground bg:background))'

###
# Configures the golang module
###
[golang]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the julia module
###
[julia]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the lua module
###
[lua]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the nodejs module
###
[nodejs]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the php module
###
[php]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the python module
###
[python]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the ruby module
###
[ruby]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the rust module
###
[rust]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''
