"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$sudo\
$directory\
$docker_context\
$aws\
$git_branch\
$fill\
$git_status\
$git_commit\
$git_state\
$php\
$python\
$golang\
$rust\
$lua\
$nodejs\
$ruby\
$typst\
$time\
$line_break\
$character
"""

[sudo]
format = '[  ](fg:black bg:bright-red) '
disabled = false

[directory]
format = '[  ](fg:black bg:green) [$path ]($style)[$read_only]($read_only_style)'
home_symbol = " ~"
read_only = '󰌾 '
read_only_style = 'fg:bright-red'
truncation_length = 2
truncation_symbol = ''

[directory.substitutions]
'~/code' = ' code'

[character]
error_symbol = '[χ](bold fg:red)'
format = '$symbol '
success_symbol = '[λ](bold fg:green)'

[fill]
style  = 'fg:bright-black'
symbol = '─'

[git_branch]
format = '[ $symbol ](bg:bright-red fg:black)[ $branch ](fg:purple)'
symbol = '󰘬'
symbol_style = 'fg:bright-red'
truncation_length = 30

[git_commit]
commit_hash_length = 4
format = " ([ 󰓹 ](fg:black bg:yellow)[ $tag ](fg:white))([ 󰜘 ](fg:black bg:yellow)[ $hash ](fg:white))"
only_detached = false
tag_disabled = true
tag_symbol = ''

[git_status]
format = '[ ](fg:yellow)$stashed$staged$deleted$renamed$modified$untracked$ahead_behind$conflicted'
stashed = '[](fg:yellow)[ $count ](fg:white)'
ahead = '[󰁝](fg:cyan)[ $count ](fg:white)'
behind = '[󰁅](fg:bright-red)[ $count ](fg:white)'
diverged = '[󰃻](fg:red)[ $ahead_count $behind_count ](fg:white)'
conflicted = '[󰅙](fg:red)[ $count ](fg:white)'
deleted = '[󰍴](fg:yellow)[ $count ](fg:white)'
renamed = '[󰑕](fg:yellow)[ $count ](fg:white)'
modified = '[󰏫](fg:yellow)[ $count ](fg:white)'
staged = '[󰐕](fg:cyan)[ $count ](fg:white)'
untracked = '[󰐕](fg:cyan)[ $count ](fg:white)'

[time]
disabled = false
format = '[ 󰥔 ](bg:bright-blue fg:black)[ $time ](fg:bright-blue)'
time_format = '%H:%M'

[aws]
disabled = true
format = '[  ](fg:black bg:red)([ $region ](fg:white))'

[docker_context]
disabled = false
format = '[ 󰡣 ](fg:black bg:blue)([ $context ](fg:white))'

[golang]
format = '[ $symbol ](fg:black bg:blue)([ $version ](fg:white))'
symbol = ''

[julia]
format = '[ $symbol ](fg:black bg:bright-red)([ $version ](fg:white))'
symbol = ''

[lua]
format = '[ $symbol ](fg:black bg:bright-red)([ $version ](fg:white))'
symbol = ''

[nodejs]
format = '[ $symbol ](fg:black bg:green)([ $version ](fg:white))'
symbol = ''

[php]
format = '[ $symbol ](fg:black bg:blue)([ $version ](fg:bright-blue))'
symbol = ''

[python]
format = '[ $symbol ](fg:black bg:green)([ $version ](fg:white))'
symbol = ''

[ruby]
format = '[ $symbol ](fg:black bg:red)([ $version ](fg:white))'
symbol = ''

[rust]
format = '[ $symbol ](fg:black bg:bright-red)([ $version ](fg:white))'
symbol = ''

[profiles]
transient = " $character "
